services:
  indexer-db:
    container_name: ${COMPOSE_PROJECT_NAME}-indexer-db
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - indexer_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "--host", "localhost", "-proot"]
      timeout: 20s
      retries: 10

  indexer:
    container_name: ${COMPOSE_PROJECT_NAME}-indexer
    image: ghcr.io/flare-foundation/flare-system-c-chain-indexer:latest
    volumes:
      - ./mounts/indexer/config.toml:/app/config.toml
    restart: unless-stopped
    depends_on:
      indexer-db:
        condition: service_healthy

  data-provider:
    container_name: ${COMPOSE_PROJECT_NAME}-data-provider
    image: ghcr.io/flare-foundation/ftso-scaling:latest
    env_file:
      - ./mounts/scaling/.env
    command: "node dist/apps/ftso-data-provider/apps/ftso-data-provider/src/main.js"
    depends_on:
      - indexer

  client:
    container_name: ${COMPOSE_PROJECT_NAME}-client
    image: ghcr.io/flare-foundation/flare-system-client:latest
    volumes:
      - ./mounts/client/config.toml:/app/config.toml
    environment:
      SYSTEM_CLIENT_SENDER_PRIVATE_KEY: ${SIGNING_PK}
      SIGNING_POLICY_PRIVATE_KEY: ${SIGNING_PK}
      PROTOCOL_MANAGER_SUBMIT_PRIVATE_KEY: ${SUBMIT_PK}
      PROTOCOL_MANAGER_SUBMIT_SIGNATURES_PRIVATE_KEY: ${SIGNATURES_PK}
      PROTOCOL_X_API_KEY_100: "abcdef"
    depends_on:
      - indexer

volumes:
  indexer_data:
