services:
  indexer-db:
    container_name: ${COMPOSE_PROJECT_NAME}-indexer-db
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/db_init.sql

  indexer:
    container_name: ${COMPOSE_PROJECT_NAME}-indexer
    image: ftso-v2-deployment/flare-system-c-indexer
    volumes:
      - ./mounts/indexer/config.toml:/app/config.toml

  data-provider:
    container_name: ${COMPOSE_PROJECT_NAME}-data-provider
    image: ftso-v2-deployment/ftso-scaling
    env_file:
      - ./mounts/scaling/.env
    command: "yarn start"

  price-provider:
    container_name: ${COMPOSE_PROJECT_NAME}-price-provider
    image: ftso-v2-deployment/ftso-scaling
    env_file:
      - ./mounts/scaling/.env
    command: "yarn start example_provider"

  client:
    container_name: ${COMPOSE_PROJECT_NAME}-client
    image: ftso-v2-deployment/flare-system-client
    volumes:
      - ./mounts/client/credentials/:/app/credentials/
      - ./mounts/client/config.toml:/app/config.toml
